TOOLS_FOLDER = './tools/'
CRESTS_FOLDER = f'{TOOLS_FOLDER}escudos/'
FONT_PATH = f"{TOOLS_FOLDER}Lato-Bold.ttf"
OPENING_VIDEO= 'opening.mp4'
VS_VIDEO = 'video-vs.mp4'
RESULTS_IMAGE = 'results-img.jpg'
RESULTS_VIDEO = 'results.mp4'
WATERMARK_IMAGE = 'logo.png'
CLIPS_LIST_FILE = 'clip_list.txt'

WATERMAR_SCALE = 0.14
WATERMARK_OFFSET_BOTTOM_Y = 175
WATERMARK_OFFSET_RIGHT_X = 215
CRESTS_SIZE = 500

RES_NAMES_FS = 70
RES_TITLE_FS = 90
RES_SCORE_FS = 200
FONT_COLOR = 'ffffff'
TEAM_A_X_ALIGN = 0.20
TEAM_B_X_ALIGN = 0.80

GOAL_A_KEY = "GOAL_TEAM_A"
GOAL_B_KEY = "GOAL_TEAM_B"
SCORE_X_CENTER = 0.14
SCORE_Y_CENTER = 0.08
SCORE_CRESTS_SIZE = 100
SCORE_CRESTS_DX = 120
SCORE_TRANSITION_TIME = 3

EXTRA_CLIPS_DURATION = 6
RECAP_FILENAME = '00 RESUMEN.mp4'
FULL_MATCH_FILENAME = '00 PARTIDO COMPLETO.mp4'
QUIET_FFMPEG = True